project:
  type: website

website:
  title: "Nada Iqbal"
  navbar:
    background: "#0056b3"  
    foreground: "white"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Projects
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3


  page-footer: 
    left: "© 2024 Nada Iqbal"

format:
  html:
    theme: 
      - cosmo  
      - brand   
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true

editor: visual


git add .
git commit -m "Updated site content"
git push

