project:
  type: website

website:
  title: "Nada Iqbal"
  navbar:
    background: "#0056b3"  
    foreground: "white"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Projects
      - text: Assignments
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.0.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - href: Lab01.qmd
            text: Lab 1
          - href: Lab02.qmd
            text: Lab 2

format:
  html:
    theme: 
      - cosmo  
      - brand   
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true
